require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - config/**/*
    - spec/rails_helper.rb
  DisplayCopNames: true
  DisplayStyleGuide: true
  CacheRootDirectory: tmp

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/I18nLocaleTexts:
  Enabled: false
